modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="${mod_issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${mod_update_url}"
displayURL="${mod_display_url}"
credits=""
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="logo.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="${jei_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="${emi_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="${jade_version_range}"
ordering="NONE"
side="BOTH"